---
title: "STAD_categorical_var"
author: "Sehyun Oh, Britney Pheng"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
    html:
        fontsize: 14pxs
        toc: true
        top-depth: 3
output: html_document
editor: visual
---

# Initial Setup

## Load packages

```{r packages, warning=FALSE, message=FALSE}
suppressPackageStartupMessages({
  # BiocManager
  library(GenomicSuperSignature)
  library(curatedTCGAData)
  library(MultiAssayExperiment)
  library(TCGAutils)
  library(ComplexHeatmap)
  
  # CRAN
  library(tidyverse) # includes dplyr, ggplot2, magrittr, tidyr
  library(magick)
  library(wordcloud)
  library(ztable)
  library(metafolio)
})
```

## Load STAD All data

```{r message=FALSE}
## SummarizedExperiment object containing STAD dataset 
stad_cancer <- readRDS("/Users/bpheng/GSS-Britney-Fieldwork-2024/data/stad_cancer.rds") # 20,501 genes x 261 samples

## Only the top 15 validated RAVs
sampleScore_sub <- read.csv("/Users/bpheng/GSS-Britney-Fieldwork-2024/data/stad_cancer_sampleScore.csv", row.names = 1) # 261 samples x 15 RAVs

## STAD categorical variables
charTb <- read.csv("/Users/bpheng/GSS-Britney-Fieldwork-2024/data/stad_cancer_char.csv", row.names = 1) # 261 samples x 182 metadata attributes (char)
```

## Prepare data

Convert character variables into the `factor` data type

```{r}
factorTb <- charTb
factorTb[sapply(factorTb, is.character)] <- lapply(factorTb[sapply(factorTb, is.character)], factor)
```

### Check the factor level

```{r}
nlevel <- sapply(factorTb, function(x) {
    res <- levels(x) %>% na.omit
    return(length(res))
})

factorTb_1_lv <- factorTb[nlevel == 1]
factorTb_2_lv <- factorTb[nlevel == 2]
factorTb_m_lv <- factorTb[nlevel > 2]

table(factorTb_m_lv$patient.microsatellite_instability_test_results.microsatellite_instability_test_result.mononucleotide_and_dinucleotide_marker_panel_analysis_status)
```

# Binomial Wilcox Test

```{r}
wilcox_test_res <- as.data.frame(matrix(nrow = ncol(factorTb_2_lv),
                                ncol = ncol(sampleScore_sub)))

rownames(wilcox_test_res) <- colnames(factorTb_2_lv)
colnames(wilcox_test_res) <- colnames(sampleScore_sub)

wtest_stad_wvalue <- wilcox_test_res
wtest_stad_pvalue <- wilcox_test_res

for (i in seq_len(ncol(sampleScore_sub))) {
  for (j in seq_len(ncol(factorTb_2_lv))) {
    ## wilcoxon test
    wilcox_test <- wilcox.test(sampleScore_sub[, i] ~ factorTb_2_lv[,j], alternative="two.sided")
    
      ## W value
      wval <- wilcox_test$statistic
      wtest_stad_wvalue[j, i] <- wval
    
    ## p-value
      pval <- wilcox_test$p.value
      wtest_stad_pvalue[j, i] <- pval
    
  }
}

batch_char_ind <- grep('analyte|analytes|portion|procurement|aliquot|uuid|barcode',
                  rownames(wtest_stad_wvalue))
wtest_stad_wvalue_2 <- wtest_stad_wvalue[-batch_char_ind,]
wtest_stad_pvalue_2 <- wtest_stad_pvalue[-batch_char_ind,]
```

```{r figures-side-4, fig.show="hold", out.width="50%"}
heatmap(as.matrix(wtest_stad_wvalue_2), main = 'STAD All Samples: Wilcoxon Test Binomial')
```

```{r}
#Only view w-values with significant p-value (<0.05)
wtest_stad_sig_wvalue <- wilcox_test_res

 for (i in seq_len(ncol(sampleScore_sub))) {
   for (j in seq_len(ncol(factorTb_2_lv))) {
     if (wilcox.test(sampleScore_sub[, i] ~ factorTb_2_lv[,j], alternative="two.sided")$p.val < 0.05) {
       wtest_stad_sig_wvalue[j, i] <- wilcox.test(sampleScore_sub[, i] ~ factorTb_2_lv[,j],
                                                  alternative="two.sided")$statistic
     }
   }
 }

na_ind <- apply(wtest_stad_sig_wvalue, 1, function(x) all(is.na(x)))
wtest_stad_sig_wvalue <- wtest_stad_sig_wvalue[!na_ind, ]
batch_char_ind_2 <- grep('analyte|analytes|portion|procurement|aliquot|uuid|barcode',
                  rownames(wtest_stad_sig_wvalue))
wtest_stad_sig_wvalue <- wtest_stad_sig_wvalue[-batch_char_ind_2, ]
```

```{r results='asis'}
# options(ztable.type='html')
# 
# ztable(wtest_stad_sig_wvalue) %>%
#   makeHeatmap(palette = 'Blues') %>%
#   print(caption='Cancer Sample W-test with p-values < 0.01')
```

# Calculate Kruskal-Wallis Test for Multinomial Factor Variables

```{r}
kruskal_wallis_res <- as.data.frame(matrix(nrow = ncol(factorTb_m_lv),
                                ncol = ncol(sampleScore_sub)))

rownames(kruskal_wallis_res) <- colnames(factorTb_m_lv)
colnames(kruskal_wallis_res) <- colnames(sampleScore_sub)

kw_stad_hvalue <- kruskal_wallis_res
kw_stad_pvalue <- kruskal_wallis_res
kw_stad_sig_hvalue <- kruskal_wallis_res

for (i in seq_len(ncol(sampleScore_sub))) {
  for (j in seq_len(ncol(factorTb_m_lv))) {
    ## Kruskal-Wallis Test
    kruskal_test <- kruskal.test(sampleScore_sub[, i] ~ factorTb_m_lv[,j])
    
    ## Kruskal-Wallis Chi-squared value
    kw_val <-  kruskal_test$statistic
    kw_stad_hvalue[j, i] <- kw_val

    ## p-value
    pval <-  kruskal_test$p.value
    kw_stad_pvalue[j, i] <- pval
    
    ## Kruskal-Wallis Chi-squared value with significant p-value (<0.05)
    if (kruskal_test$p.value < 0.05) {
      kw_stad_sig_hvalue[j,i] <- kruskal_test$statistic
    }
  }
}

batch_char_ind <- grep('analyte|analytes|portion|procurement|aliquot|uuid|barcode',
                  rownames(kw_stad_hvalue))
kw_stad_hvalue <- kw_stad_hvalue[-batch_char_ind,]
kw_stad_pvalue <- kw_stad_pvalue[-batch_char_ind,]
kw_stad_sig_hvalue <- kw_stad_sig_hvalue[-batch_char_ind,]

write.csv(kw_stad_hvalue, "/Users/bpheng/GSS-Britney-Fieldwork-2024/data/kw_stad_hvalue.csv")
write.csv(kw_stad_pvalue, "/Users/bpheng/GSS-Britney-Fieldwork-2024/data/kw_stad_pvalue.csv")
write.csv(kw_stad_sig_hvalue, "/Users/bpheng/GSS-Britney-Fieldwork-2024/data/kw_stad_sig_hvalue.csv")
```

```{r}
for (i in seq_len(ncol(sampleScore_sub))) {
  print(colnames(sampleScore_sub)[i])
    xy <- pairwise.wilcox.test(sampleScore_sub[, i], factorTb_m_lv[,"patient.microsatellite_instability_test_results.microsatellite_instability_test_result.mononucleotide_and_dinucleotide_marker_panel_analysis_status"], p.adjust.method = "bonferroni")
    print(xy)
}
```

```{r figures-side-5, fig.show="hold", out.width="50%"}
heatmap(as.matrix(kw_stad_hvalue), main = 'STAD All Samples: Kruskal-Wallis Test')

heatmap(as.matrix(kw_stad_hvalue[40:50,]), main = 'STAD Cancer Samples: Kruskal-Wallis Test')
```

```{r}
kw_stad_sig_hvalue[1]

kw_stad_sig_hvalue[47,which(!is.na(kw_stad_sig_hvalue[47,]) & kw_stad_sig_hvalue[47,] > 40)] #RAV324, RAV868, RAV2344, RAV517
```
